#!/usr/bin/env python
"""Rebuild compact main-table snapshots from frozen release summaries.

This script intentionally avoids raw datasets, hosted-model calls, and private
provider metadata. It reads only the lightweight CSV files under
artifacts/summaries/ and writes a reviewer-facing LaTeX snapshot under
artifacts/tables/.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


MAIN_ORDER = [
    "LLM-only / No Retrieval",
    "One-step Dense RAG",
    "Multi-query RAG",
    "Single-query Reformulation RAG",
    "BM25 RAG",
    "BM25 + Dense Hybrid",
    "Evidence-guided Iterative Retrieval",
    "HyDE-style RAG",
]

QUERY_ORDER = [
    "Question only",
    "Single rewritten query",
    "Question + rewritten query",
    "Hypothetical only",
    "Question + hypothetical",
]

EQUAL_BUDGET_ORDER = [
    "keyword_expansion",
    "direct_rewrite",
    "question_decomposition",
    "document_like_passage",
]

EQUAL_BUDGET_LABELS = {
    "keyword_expansion": "Keyword/entity expansion",
    "direct_rewrite": "Direct rewrite",
    "question_decomposition": "Question decomposition",
    "document_like_passage": "Document-like passage",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def fmt(value: str, digits: int = 4) -> str:
    if value == "" or value is None:
        return "--"
    return f"{float(value):.{digits}f}"


def row(values: list[str]) -> str:
    return " & ".join(values) + r" \\"


def write_table_section(lines: list[str], title: str) -> None:
    lines.append(f"% {title}")
    lines.append(r"\begin{tabular}{lrrrrr}")
    lines.append(r"\toprule")
    lines.append(row(["Method", "Any hit@10", "All hit@10", "Recall@10", "EM", "F1"]))
    lines.append(r"\midrule")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output .tex path. Defaults to artifacts/tables/rebuilt_main_tables.tex.",
    )
    args = parser.parse_args()

    root = args.root
    summaries = root / "artifacts" / "summaries"
    out = args.out or root / "artifacts" / "tables" / "rebuilt_main_tables.tex"
    out.parent.mkdir(parents=True, exist_ok=True)

    main_rows = read_csv(summaries / "ircot_test500_qwen_results.csv")
    ablation_rows = read_csv(summaries / "hyde_mechanism_ablation_hotpotqa_test500.csv")
    equal_rows = read_csv(
        summaries
        / "equal_budget_query_diagnostic"
        / "equal_budget_query_retrieval_summary.csv"
    )
    equal_contrasts = read_csv(
        summaries
        / "equal_budget_query_diagnostic"
        / "equal_budget_query_pairwise_bootstrap.csv"
    )
    support_rows = read_csv(
        summaries / "supporting_paragraph_audit" / "supporting_paragraph_metrics.csv"
    )

    by_method = {r["method"]: r for r in main_rows}
    by_variant = {r["variant"]: r for r in ablation_rows}

    lines: list[str] = [
        "% Auto-generated by scripts/rebuild_main_tables_from_summaries.py.",
        "% Source files are frozen lightweight summaries under artifacts/summaries/.",
        "",
    ]

    write_table_section(lines, "Table 1 snapshot: HotpotQA main results")
    for method in MAIN_ORDER:
        r = by_method[method]
        lines.append(
            row(
                [
                    method,
                    fmt(r["any_hit"]),
                    fmt(r["all_hit"]),
                    fmt(r["mean_recall"]),
                    fmt(r["em"]),
                    fmt(r["f1"]),
                ]
            )
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")

    write_table_section(lines, "Query-composition snapshot: HotpotQA")
    for variant in QUERY_ORDER:
        r = by_variant[variant]
        lines.append(
            row(
                [
                    variant,
                    fmt(r["any_hit"]),
                    fmt(r["all_hit"]),
                    fmt(r["mean_recall"]),
                    fmt(r["reader_em"]),
                    fmt(r["reader_f1"]),
                ]
            )
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")

    lines.append("% Equal-budget retrieval-only snapshot")
    lines.append(r"\begin{tabular}{llrrrr}")
    lines.append(r"\toprule")
    lines.append(
        row(["Dataset", "Generated query form", "Mean words", "Any hit@10", "All hit@10", "Recall@10"])
    )
    lines.append(r"\midrule")
    for dataset in ["HotpotQA", "2WikiMultihopQA"]:
        dataset_rows = {
            r["query_mode"]: r for r in equal_rows if r["dataset"] == dataset
        }
        for mode in EQUAL_BUDGET_ORDER:
            r = dataset_rows[mode]
            lines.append(
                row(
                    [
                        "2Wiki" if dataset == "2WikiMultihopQA" else dataset,
                        EQUAL_BUDGET_LABELS[mode],
                        fmt(r["mean_generation_words"], 3),
                        fmt(r["any_hit@10"]),
                        fmt(r["all_support_hit@10"]),
                        fmt(r["supporting_title_recall@10"]),
                    ]
                )
            )
        if dataset == "HotpotQA":
            lines.append(r"\midrule")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")

    lines.append("% Equal-budget paired contrasts: document-like passage minus baseline")
    lines.append(r"\begin{tabular}{llrrr}")
    lines.append(r"\toprule")
    lines.append(row(["Dataset", "Baseline form", "N", "Delta All hit@10 [95\\% CI]", "Delta Recall@10 [95\\% CI]"]))
    lines.append(r"\midrule")
    for r in equal_contrasts:
        dataset = "2Wiki" if r["dataset"] == "2WikiMultihopQA" else r["dataset"]
        baseline = EQUAL_BUDGET_LABELS[r["baseline_query_mode"]]
        all_ci = (
            f"{fmt(r['all_support_hit@10_delta'])} "
            f"[{fmt(r['all_support_hit@10_ci_low'])}, {fmt(r['all_support_hit@10_ci_high'])}]"
        )
        recall_ci = (
            f"{fmt(r['supporting_title_recall@10_delta'])} "
            f"[{fmt(r['supporting_title_recall@10_ci_low'])}, {fmt(r['supporting_title_recall@10_ci_high'])}]"
        )
        lines.append(row([dataset, baseline, r["n"], all_ci, recall_ci]))
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")

    lines.append("% Supporting-paragraph audit snapshot")
    lines.append(r"\begin{tabular}{lllrrrr}")
    lines.append(r"\toprule")
    lines.append(
        row(
            [
                "Dataset",
                "Panel",
                "Method",
                "Title all-hit",
                "Paragraph all-hit",
                "Title recall",
                "Paragraph recall",
            ]
        )
    )
    lines.append(r"\midrule")
    for r in support_rows:
        lines.append(
            row(
                [
                    r["dataset"],
                    r["family"],
                    r["method"],
                    fmt(r["title_all_hit_at10"]),
                    fmt(r["paragraph_all_hit_at10"]),
                    fmt(r["title_recall_at10"]),
                    fmt(r["paragraph_recall_at10"]),
                ]
            )
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {out.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
